import type { Metadata } from "next";
import { LegalPage, H2, P, UL } from "../legal-page";
export const metadata: Metadata = { title: "Privacy Policy", alternates: { canonical: "/privacy" }, description: "How Counted handles analytics, account information, authentication, and billing." };
export default function Privacy() { return <LegalPage title="Privacy Policy" updated="September 7, 2026">
<P>Counted is a product of Iceglobe Enterprises LLC ("Counted," "we," "us"). Counted is built to collect as little as possible. This policy explains what we collect, what we deliberately don’t, and the choices you have.</P>
<H2>Our privacy stance</H2><UL><li><strong>No tracking cookies or fingerprinting.</strong> We do not create cross-site identifiers for analytics.</li><li><strong>Ephemeral visits.</strong> The SDK keeps its visit id in memory. Event records carry that id to group activity during the visit; the SDK does not persist it in cookies or local storage.</li><li><strong>You control event properties.</strong> Do not send personal data in event names, properties, URLs, paths, or labels. Counted does not derive identity. If you choose to call <code>identify()</code>, use an opaque identifier you already control, not an email address or other directly identifying value.</li></UL>
<H2>Information we collect</H2><P><strong>Account information.</strong> The Counted app stores your email, name, verification state, and workspace membership. If you set a password, it stores a password hash, not the password. Magic-link sign-in and transactional messages use your email address.</P><P><strong>Optional social sign-in.</strong> When a configured Google or GitHub provider is selected, you leave Counted to authenticate with that provider. It learns of the sign-in and its own policy applies. Counted receives your provider account id, email and verification information, and profile details such as name and avatar. The authentication service may store returned OAuth tokens. Google requests OpenID, email, and profile access; GitHub requests profile and email access.</P><P><strong>Analytics events.</strong> We receive the names and properties you choose to send, coarse system properties your SDK supplies, and an ephemeral visit id. Our API uses the request IP transiently to derive a country and enforce abuse limits. It does not store the IP or user-agent in analytics. Country lookup runs locally; no IP is sent to a geolocation provider. Client-supplied country values are ignored.</P><P><strong>Authentication and abuse prevention.</strong> Console sessions do not persist IP addresses or user-agent strings. Per-address authentication rate limits are held in bounded, expiring process memory, rather than in the database.</P><P><strong>The public site.</strong> These public pages do not set tracking cookies or load an analytics tracker. Following a link to the signed-in app starts a separate authentication flow.</P><P><strong>Billing.</strong> Stripe processes paid plans. We store billing references and subscription state, not card details. Stripe’s handling is governed by its own privacy policy.</P>
<H2>Authentication cookies</H2><P>We use no cookies for analytics or advertising. The app uses necessary cookies during sign-in and to keep your session authenticated; some are set before sign-in completes. Login sessions can last up to 30 days and are refreshed no more than once a day. These cookies do not connect analytics visits or track you across websites.</P>
<H2>How we use information</H2><UL><li>To provide and secure Counted.</li><li>To manage accounts, workspace access, and subscriptions.</li><li>To send transactional email through Resend, including sign-in links and service notices.</li></UL><P>We do not sell your data or use it to build advertising profiles. Cookie-free analytics does not remove your responsibility to assess the data you send and the legal requirements that apply to your use.</P>
<H2>Subprocessors</H2><P>The vendors needed to operate the hosted service include Stripe for payments, Resend for transactional email, and our hosting provider for application and database infrastructure. Their processing is subject to their own terms. A social provider is involved only when you choose that sign-in method.</P>
<H2>Data retention</H2><P>Event retention is 180 days on Free and 730 days on Pro, subject to project retention settings. Deduplication digests prevent retried events from being counted twice; they contain no event properties or visit ids and remain until the project is deleted. Account data is retained while your account is active and can be deleted through account closure or a data request.</P><P>To close your account, first leave your workspaces or transfer ownership. Closing an account does not delete workspace data that remains under another owner.</P>
<H2>Your rights</H2><P>Depending on where you live, you may have rights to access, correct, export, or delete personal data and to object to processing. Contact <a href="mailto:privacy@counted.dev">privacy@counted.dev</a> to make a request.</P>
<H2>Self-hosting</H2><P>When you host your own instance, you control its infrastructure and processing. This hosted-service policy does not govern data held by your own installation.</P>
<H2>Changes and contact</H2><P>We will update this policy as the product evolves and revise the date above. Questions or data requests: <a href="mailto:privacy@counted.dev">privacy@counted.dev</a>.</P>
</LegalPage>; }
