/**
 * Running generated SQL on the `pg` pool, under a deadline that is real.
 *
 * `QueryOptions.deadline` is described in the port as a hard ceiling an adapter
 * "must honour and return `Timeout`, not hang". Honouring it needs both halves:
 * a client-side timer alone leaves the query running on the server, burning a
 * connection and CPU for a page nobody is looking at any more, and a server-
 * side `statement_timeout` alone does not cover the time spent waiting for a
 * free connection. So the budget is spent down across both.
 *
 * Used by the catalog, whose two reads are hand-written SQL over the summary
 * and staging tables. The engine's reads go through litics' own reader and
 * never come here.
 *
 * Every read runs in one `BEGIN … READ ONLY` transaction, because `SET LOCAL`
 * is the only way to change `statement_timeout` for a query without leaving
 * the setting behind on a pooled connection that some other request picks up
 * next. A `SET` without `LOCAL` here would silently hand every subsequent user
 * of that connection a timeout they never asked for.
 */

import type { SqlStatement } from "@litics/core";
import type { EngineFailure, QueryOptions } from "@counted/analytics-ports";
import { Duration } from "@counted/kernel";

export type Row = Record<string, unknown>;

export type ExecOutcome =
  | { readonly ok: true; readonly results: readonly (readonly Row[])[] }
  | { readonly ok: false; readonly error: EngineFailure };

/**
 * The narrowest shape this adapter needs from a `pg` pool.
 *
 * Declared structurally rather than as `Pick<Pool, "connect">` for two
 * reasons: nothing here has to import the driver, and a test can hand in a
 * fake without a cast. A real `pg.Pool` satisfies it, and `execute.test.ts`
 * asserts that at compile time so the shape cannot drift away from the driver
 * unnoticed.
 */
export interface QueryClient {
  query<R extends Row = Row>(sql: string, values?: unknown[]): Promise<{ rows: R[] }>;
  /** `true` destroys the connection instead of returning it to the pool. */
  release(destroy?: boolean): void;
}

export interface QueryPool {
  connect(): Promise<QueryClient>;
}

class Aborted extends Error {}

/**
 * Resolve when the promise does, or reject as soon as the signal fires.
 *
 * The underlying query keeps running until the connection is destroyed, which
 * is what the caller does on the way out — there is no way to cancel a `pg`
 * query in flight on the same connection.
 */
const untilAborted = async <T>(work: Promise<T>, signal: AbortSignal | undefined): Promise<T> => {
  if (signal === undefined) return work;
  if (signal.aborted) throw new Aborted();
  return await new Promise<T>((resolve, reject) => {
    const onAbort = (): void => reject(new Aborted());
    signal.addEventListener("abort", onAbort, { once: true });
    work.then(resolve, reject).finally(() => signal.removeEventListener("abort", onAbort));
  });
};

/**
 * Postgres error codes that mean something specific enough to say.
 *
 * Anything unrecognised becomes `Unavailable` rather than `InvalidQuery`: the
 * SQL was generated by litics from a config this package validated at import,
 * so "the query was wrong" is nearly always the less likely explanation.
 */
const failureFor = (cause: unknown): EngineFailure => {
  const code = typeof cause === "object" && cause !== null && "code" in cause
    ? String((cause as { code?: unknown }).code)
    : "";
  const detail = cause instanceof Error ? cause.message : String(cause);

  switch (code) {
    case "57014": // query_canceled — statement_timeout fired.
      return { kind: "Timeout", budget: Duration.ZERO };
    case "42P01": // undefined_table
    case "3F000": // invalid_schema_name
      return {
        kind: "Unavailable",
        detail: `the analytics schema is not present — run the litics migrations (${detail})`,
      };
    case "53300": // too_many_connections
    case "53400": // configuration_limit_exceeded
    case "57P01": // admin_shutdown
    case "57P02": // crash_shutdown
    case "57P03": // cannot_connect_now
      return { kind: "Unavailable", detail };
    case "42501": // insufficient_privilege
      return { kind: "Unavailable", detail: `the analytics role lacks a grant (${detail})` };
    default:
      return { kind: "Unavailable", detail };
  }
};

/**
 * A caller that walked away.
 *
 * `EngineFailure` has no "cancelled" kind and inventing one would ripple
 * through the contract's error table for a case the client already knows
 * about — it is the one that aborted. `Unavailable` with a detail that says so
 * keeps the shape and does not claim the engine timed out, which would be a
 * different instruction to whoever reads the log.
 */
const cancelled: EngineFailure = {
  kind: "Unavailable",
  detail: "the caller cancelled the query before it finished",
};

/**
 * Run every statement on one connection, in order, sharing one budget.
 *
 * Statements are handed to `pg` exactly as litics produced them — `$1..$n`
 * placeholders with the parameters alongside. Nothing here interpolates a
 * value into SQL; the only interpolation is `statement_timeout`, which is a
 * rounded integer this function computes.
 */
export const execute = async (
  pool: QueryPool,
  statements: readonly SqlStatement[],
  options: QueryOptions,
): Promise<ExecOutcome> => {
  const budget = Math.max(1, Math.ceil(Duration.toMillis(options.deadline)));
  const timeout: EngineFailure = { kind: "Timeout", budget: options.deadline };
  const deadlineAt = Date.now() + budget;
  if (statements.length === 0) return { ok: true, results: [] };

  let client: QueryClient;
  try {
    client = await untilAborted(pool.connect(), options.signal);
  } catch (cause) {
    if (cause instanceof Aborted) return { ok: false, error: cancelled };
    return { ok: false, error: failureFor(cause) };
  }

  // `true` destroys the connection instead of returning it to the pool, which
  // is how an in-flight query actually stops: Postgres notices the socket
  // close and terminates the backend.
  let discard = false;
  try {
    // REPEATABLE READ, not the default READ COMMITTED: a read that touches
    // segments and then the staging tail must see one snapshot of both. At
    // READ COMMITTED each statement sees its own, and a pack committing in
    // between moves rows out of staging after they were counted there — or
    // before they were, depending on statement order. Either way a number
    // comes back that is silently wrong by exactly one batch.
    await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");
    const results: Row[][] = [];
    for (const statement of statements) {
      const remaining = deadlineAt - Date.now();
      if (remaining <= 0) {
        discard = true;
        return { ok: false, error: timeout };
      }
      await client.query(`SET LOCAL statement_timeout = ${Math.ceil(remaining)}`);
      const result = await untilAborted(
        client.query<Row>(statement.sql, statement.parameters as unknown[]),
        options.signal,
      );
      results.push(result.rows);
    }
    await client.query("COMMIT");
    return { ok: true, results };
  } catch (cause) {
    discard = true;
    if (cause instanceof Aborted) return { ok: false, error: cancelled };
    const failure = failureFor(cause);
    // A statement_timeout cancellation knows it was a timeout but not what the
    // budget was; the budget is this function's to supply.
    return { ok: false, error: failure.kind === "Timeout" ? timeout : failure };
  } finally {
    client.release(discard);
  }
};

/**
 * Read a `float8` column, or `null` if it is not a finite number.
 *
 * `null` rather than a zero fallback. litics casts every aggregate to float8
 * exactly so a JS number comes back, and if one does not, something below this
 * layer changed — a value of zero would render as "nothing happened", which is
 * the one answer that must never be produced by a failure.
 */
export const numberAt = (row: Row, column: string): number | null => {
  const value = row[column];
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return null;
};

/** Read the `bucket` column, which `pg` parses into a `Date`. */
export const timestampAt = (row: Row, column: string): Date | null => {
  const value = row[column];
  if (value instanceof Date) return value;
  if (typeof value === "string") {
    const parsed = new Date(value);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }
  return null;
};
