import document from "../../../openapi.json";
import type { ApiDocument } from "./model";

/** This is the artifact generated by oRPC and checked for drift in CI. */
export const apiDocument = document as unknown as ApiDocument;
export {
  operationsOf,
  operationGroupsOf,
  resolveSchema,
  initialValue,
  variantLabel,
  variantIndex,
  parameterSchema,
  requestSchema,
  buildRequest,
  buildCustomRequest,
  validateValue,
} from "./model";
export type {
  ApiDocument,
  Operation,
  Parameter,
  Schema,
  Json,
  RequestCredential,
} from "./model";
